# Generated by Django 5.0.7 on 2024-07-24 08:33

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="titre")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["title"],
                        unique=True,
                        verbose_name="event slug",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="description")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event/images/events",
                        verbose_name="Image de l'événement",
                    ),
                ),
                (
                    "date_begin",
                    models.DateField(
                        blank=True, null=True, verbose_name="date de début"
                    ),
                ),
                (
                    "date_finish",
                    models.DateField(blank=True, null=True, verbose_name="date de fin"),
                ),
                (
                    "published_on",
                    models.DateField(blank=True, null=True, verbose_name="publié le"),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="publié"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="auteur",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "articles",
                "ordering": ["-published_on"],
            },
        ),
    ]
