# Generated by Django 5.0.7 on 2024-07-25 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-published_on"],
                "verbose_name_plural": "événements",
            },
        ),
    ]
