# Generated by Django 5.0.7 on 2024-07-22 14:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Articles",
            new_name="Article",
        ),
    ]
