# Generated by Django 5.0.7 on 2024-07-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_author_alter_article_published_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article/images/articles",
                verbose_name="Image de l'article",
            ),
        ),
    ]
