# Generated by Django 5.0.7 on 2024-07-25 08:52

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-mail"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["contact_email", "created_at"],
                        unique=True,
                        verbose_name="contact slug",
                    ),
                ),
                ("content", models.TextField(verbose_name="message")),
                (
                    "reason",
                    models.CharField(
                        choices=[("CONTACT", "Contact"), ("BUG", "Remontée de bug")],
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "contacts",
            },
        ),
    ]
