# Generated by Django 5.0.7 on 2024-07-25 11:09

import blog.contacts.models
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="reason",
            field=models.CharField(
                choices=[("CONTACT", "Contact"), ("BUG", "Remontée de bug")],
                max_length=15,
                verbose_name="motif",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from=blog.contacts.models.slugify_with_date,
                unique=True,
                verbose_name="contact slug",
            ),
        ),
    ]
